Repository bitcointranscripts/bitcointranscripts, pull requests merged in 2024-02, with the labels that each got.

#396 Add explaining-rgb-tokens-the-technical-side-of-bitcoin to bitcoin-magazine/bitcoin-explained
  bitcoin-magazine/bitcoin-explained/explaining-rgb-tokens.md
Labels: ready to review

#387 Add bitcoin-core-0.21.0-new-release to bitcoin-magazine/bitcoin-explained
  bitcoin-magazine/bitcoin-explained/bitcoin-core-v0-21.md
Labels: ready to review

#362 Add demystifying-and-understanding-bitcoin-core-development to bitcoin-review-podcast
  bitcoin-review-podcast/demystifying-and-understanding-bitcoin-core-development.md
Labels: waiting for changes

#395 Add static-invoices-in-lightning:-a-deep-dive-and-comparison-of-bolt11-invoices-lnurl-offers-and-amp to advancing/2021
  advancing-bitcoin/2022/static-invoices-in-lightning.md
  twitter_handles.json
Labels: waiting for changes

#378 Add bitcoin-core-22.0-explained to bitcoin-magazine/bitcoin-explained
  bitcoin-magazine/bitcoin-explained/bitcoin-core-v22-explained.md
Labels: waiting for changes

#377 Add accounts-for-bitcoin-easypaysy! to bitcoin-magazine/bitcoin-explained
  bitcoin-magazine/bitcoin-explained/accounts-for-bitcoin-easypaysy.md
Labels: waiting for changes

#380 Add cashu-and-fedimint:-ecash-bitcoin's-layer-3-and-scalability to bitcoin-review-podcast
  bitcoin-review-podcast/cashu-and-fedimint.md
  twitter_handles.json
Labels: waiting for changes

#364 Add bitcoin-core-24.0 to bitcoin-magazine/bitcoin-explained
  bitcoin-magazine/bitcoin-explained/bitcoin-core-v24.md
Labels: ready to review

#414 Add exploring-p2p-hashrate-markets-v2 review to bitcoinplusplus/layer-2
  bitcoinplusplus/layer-2/exploring-p2p-hashrate-markets-v2.md
Labels: waiting for changes

#412 Add covenants review to bitcoin-design/learning-bitcoin-and-design
  bitcoin-design/learning-bitcoin-and-design/covenants.md
Labels: exceptional review

#417 Add the-block-1-983-702-problem review to bitcoin-explained
  bitcoin-explained/the-block-1-983-702-problem.md
Labels: waiting for changes

#422 Add onboarding-bitcoin-and-lightning-developers review to adopting-bitcoin/2021
  adopting-bitcoin/2021/onboarding-bitcoin-and-lightning-developers.md
Labels: exceptional review
